# Disable non-webhook triggers
trigger: none
pr: none

# Webhook resource that triggers pipeline
resources:
  webhooks:
    - webhook: WebookDemoTrigger           ### Webhook name
      connection: myscforgit    ### Incoming webhook service connection name

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      # Write parameters from webhook payload to console
      Write-Host ${{ parameters.WebookDemoTrigger.app_name }}
      Write-Host ${{ parameters.WebookDemoTrigger.environment }} 