trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Get the commit ID of the latest commit
          commit_id=$(git log --pretty=format:'%H' -n 1)
           
          echo "The latest commit ID is: $commit_id"
          git checkout testing
          git cherry-pick $commit_id


