# Disable non-webhook triggers
trigger: none
pr: none

# Webhook resource that triggers pipeline
resources:
  webhooks:
    - webhook: gitwebhook01           ### Webhook name
      connection: githubservice    ### Incoming webhook service connection name

pool:
  vmImage: ubuntu-latest

steps:  
# - script: echo "${{ parameters.WebHook.resource.message.title }}"
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "commitid from pr is ${{ parameters.gitwebhook01.commits[0].id }}"
      echo "repositoryname from pr is ${{ parameters.gitwebhook01.repository.name }}"
      echo "targeted branch ${{ parameters.gitwebhook01.ref }}"
      targetCommitId="${{ parameters.gitwebhook01.commits[0].id }}"
      targetRepo="${{ parameters.gitwebhook01.repository.name }}"
      ref="${{ parameters.gitwebhook01.ref }}"
      triggeredBranch=$(awk -F'/' '{print $NF}' <<< "$ref")
      echo "$commitedbranch"
      requiredBranchRegExpr="master"
       if [[ $triggeredBranch =~ $requiredBranchRegExpr ]]; 
        then
            set -x
            Targetbranch=testing
            echo "Targetbranch is $Targetbranch"
            git config --global user.email "vengalasanjay000@gmail.com"
            git config --global user.name "vengalasanjay"
            git clone https://github.com/vengalasanjay/php-app-terraform.git
            cd "$targetRepo"
            git checkout $Targetbranch
            if git cherry-pick -m 1 $targetCommitId --allow-empty;
            then
                cherrypicstatus=success
            else
                cherrypicstatus=failed
            fi
            echo "$cherrypicstatus"
            git status
            git push https://$(gitusername):$(gitpass)@github.com/vengalasanjay/php-app-terraform.git
            git push https://username:password@github.com/<username>/<repository>

       else
           echo "this execution is not triggered for release branch"
       fi
       echo $cherrypicstatus



