# Disable non-webhook triggers
trigger: none
pr: none

# Webhook resource that triggers pipeline
resources:
  webhooks:
    - webhook: githook           ### Webhook name
      connection: mygitsc    ### Incoming webhook service connection name

pool:
  vmImage: ubuntu-latest

steps:  
- script: echo ${{ parameters.WebHook.resource.message.title }}