trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Get the commit ID of the latest commit
          git config --global user.email "you@example.com"
          git config --global user.name "sanjay"


          commit_id=$(git log --pretty=format:'%H' -n 1)
           
          echo "The latest commit ID is: $commit_id"
          git clone https://github.com/vengalasanjay/php-app-terraform.git
          git checkout testing
          git cherry-pick $commit_id


