# Disable non-webhook triggers
trigger: none
pr: none

# Webhook resource that triggers pipeline
resources:
  webhooks:
    - webhook: githubincoming           ### Webhook name
      connection: githubservice    ### Incoming webhook service connection name

pool:
  vmImage: ubuntu-latest

steps:  
# - script: echo "${{ parameters.WebHook.resource.message.title }}"
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'