# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      az extension add --name azure-devops
      az extension update --name azure-devops
      echo "$(azurepat)" | az devops login --organization https://dev.azure.com/sriajay/
            
          az devops service-endpoint show --id f6f86d7a-8978-4e32-9f24-f7bd962d63e5 -p Autocascading --detect
