
trigger: 
  - master

resources:
  webhooks:
    - webhook: prpushtoreleasebranch
      connection: github.com_vengalasanjay

pool:
  vmImage: ubuntu-latest
steps:
-
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "repository name from pr is ${{ parameters.prpushtoreleasebranch.repository.name }}"'