# Disable non-webhook triggers
trigger: none
pr: none

# Webhook resource that triggers pipeline
resources:
  webhooks:
    - webhook: WebookDemoTrigger 
      connection: myscforgit    ### Incoming webhook service connection name

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "PR-Title is ${{ parameters.prpushtoreleasebranch.push.changes[0].new.target.message }}"
              echo "commitid from pr is ${{ parameters.prpushtoreleasebranch.push.changes[0].new.target.hash }}"
              echo "repositoryname from pr is ${{ parameters.prpushtoreleasebranch.repository.full_name }}"
              echo "repository from pr is ${{ parameters.prpushtoreleasebranch.repository.name }}"