trigger:
  - master

pool:
  vmImage: ubuntu-latest

jobs:
  - job: PrintPayload
    displayName: 'Print GitHub Payload'
    steps:
      - checkout: self

      - script: |
          echo "Received GitHub webhook payload:"
          echo $(cat $env:SYSTEM_PULLREQUEST_TARGETBRANCH)  # Print the payload data
        displayName: 'Print Payload'
