
trigger: 
  - master


pool:
  vmImage: ubuntu-latest
steps:
-
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "repository name from pr is ${{ parameters.prpushtoreleasebranch.repository.name }}"'